### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by Jems-Chawin** [vonfeng/DeepMapMatching#1]
Hello, I've been examining your repository and noticed that the data folder used for running the code and training the model is not included. This information would be very helpful for those trying to reproduce your results or build upon your work. If the data cannot be made publicly available on GitHub, could you at least provide a sample of the data format that you used? Thanks a lot!

**Comment by vonfeng** [comment]
Hello, thank you for your interest in our repository. We apologize for the inconvenience. Due to the privacy constraints of the dataset, we are unable to host it on GitHub. 

However, we add a sample of the data format to the repository to assist others in understanding how to structure their data for use with our code. You can find it in the [data](https://github.com/vonfeng/DeepMapMatching/tree/main/data). 

Thank you for your patience and understanding!
